build:
  version: "1.0"

accounts:
  message: "Welcome to Tally accounts related local APIs "
  contactDetails:
    name: "Galvin Glow - Developer"
    email: "galvin@tally.in"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345