build:
  version: "2.0"

cards:
  message: "Welcome to Tally cards related local APIs "
  contactDetails:
    name: "Leo Trousseau - Tester"
    email: "leo@tally.in"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345